version: '3.1'

services:

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: newbase
      POSTGRES_USER: vasya
      POSTGRES_PASSWORD: Statoil2025
    volumes:
      - ./data:/var/lib/postgresql
    ports:
      - '5432:5432'
